// dereference a null pointer.
// ulimit -S -c unlimited   to enable core dump creation.
// expect a core dump.

int main(void){
  int * pData = 0;
  return *pData;
}
/***
gcc -g -o  dataabort databort.c

bennie@bennie-VirtualBox:~/Projects/threeeasypieces/Misc$ ./dataabort 
Segmentation fault (core dumped)
bennie@bennie-VirtualBox:~/Projects/threeeasypieces/Misc$ gdb -q -nh ./dataabort core
Reading symbols from ./dataabort...done.
[New LWP 3455]
Core was generated by `./dataabort'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005642c862d60a in main () at databort.c:7

warning: Source file is more recent than executable.
7	  return *pData;
(gdb) bt
#0  0x00005642c862d60a in main () at databort.c:7

**/
